### ISSUE TITLE
Catching git-commit from zsh

### ISSUE THREAD

**Issue by atuttle** [IonicaBizau/git-stats#1] opened 2015-02-09 15:03 UTC
After adding your sample script for catching `git commit` to my .zshrc file:

```
$ git status
bash: -c: line 24: syntax error near unexpected token `status'
bash: -c: line 24: `} status'
```

So for now I'll have to live without it. Would be nice if there was an alternative, for zsh users though. :)

**Comment by IonicaBizau** [comment] 2015-02-09 15:09
What platform? I only tested this on Ubuntu 14.10 and I have no device to test it on OS X... :cry: 

Since it's a syntax error, something should be in the override function, not being related to `zsh` (tested it inside of a `zsh` session and it works fine).

Would be nice to output the `$cmdToRun`  variable before running it:

```sh
...
  echo $cmdToRun # Add this and post the output in the issue
  bash -c "$cmdToRun"
...
```

**Comment by atuttle** [comment] 2015-02-09 15:32
I'm on OSX. I added `echo $cmdToRun` right before `bash -c $cmdToRun`, but that doesn't seem to fix it. It's probably not helping that I'm using Oh-My-Zsh and I have a git command in my prompt (the green area):

![image](https://cloud.githubusercontent.com/assets/46990/6109129/ac6dee24-b046-11e4-854c-f295c9f6e920.png)

If I ignore the error embedded in my prompt, and run a `git status` I see this:

![image](https://cloud.githubusercontent.com/assets/46990/6109147/d60619e6-b046-11e4-8ade-9553eaf34dd5.png)

**Comment by IonicaBizau** [comment] 2015-02-09 15:56
Oh, it seems that when it tries to run `git` it gets the overridden value (the function we defined). :open_mouth: 

Can you check if the `which git` returns the `git` function we defined?

Maybe we can use the `command` or `alias` commands to make this process better.

**Comment by atuttle** [comment] 2015-02-09 15:58
Yes, `which git` does show the method we're creating:

![image](https://cloud.githubusercontent.com/assets/46990/6109680/90cf1158-b04a-11e4-8911-5402c5aff928.png)

**Comment by IonicaBizau** [comment] 2015-02-09 16:02
OK, so let's try the `command` command:

```sh
# My own Git
git() {
  cmd=$1
  shift
  extra=""

  quoted_args=""
  whitespace="[[:space:]]"
  for i in "$@"
  do
      quoted_args="$quoted_args \"$i\""
  done

  cmdToRun="git "$cmd" $quoted_args"
  cmdToRun=`echo $cmdToRun | sed -e 's/^ *//' -e 's/ *$//'`
  bash -c "$cmdToRun"
  if [ $? -eq 0 ]; then
    # Commit stats
    if [ "$cmd" == "commit" ]; then
      commit_hash=`git rev-parse HEAD`
      repo_url=`git config --get remote.origin.url`
      commit_date=`git log -1 --format=%cd`
      commit_data="\"{ \"date\": \"$commit_date\", \"url\": \"$repo_url\", \"hash\": \"$commit_hash\" }\""
      git-stats --record "$commit_data"
    fi
  fi
}
```

**Comment by atuttle** [comment] 2015-02-09 16:06
Better... still not quite there.

![image](https://cloud.githubusercontent.com/assets/46990/6109821/a2cbaf46-b04b-11e4-8fcd-89a694a65ad0.png)

**Comment by IonicaBizau** [comment] 2015-02-09 16:10
Whoups, in the previous code I didn't use `command`.

So, let's try it (this will also output the command that is run by `command`):

```sh
git() {
  cmd=$1
  shift
  extra=""

  quoted_args=""
  whitespace="[[:space:]]"
  for i in "$@"
  do
      quoted_args="$quoted_args \"$i\""
  done

  cmdToRun="git "$cmd" $quoted_args"
  cmdToRun=`echo $cmdToRun | sed -e 's/^ *//' -e 's/ *$//'`
  echo ">>> $cmdToRun"
  command $cmdToRun
  if [ $? -eq 0 ]; then
    # Commit stats
    if [ "$cmd" == "commit" ]; then
      commit_hash=`git rev-parse HEAD`
      repo_url=`git config --get remote.origin.url`
      commit_date=`git log -1 --format=%cd`
      commit_data="\"{ \"date\": \"$commit_date\", \"url\": \"$repo_url\", \"hash\": \"$commit_hash\" }\""
      git-stats --record "$commit_data"
    fi
  fi
}
```

**Comment by atuttle** [comment] 2015-02-09 16:12
Two steps forward, one step back: (I did think it was a little odd that you mentioned it above the code but I couldn't find it in the code ;))

![image](https://cloud.githubusercontent.com/assets/46990/6109938/858cdf08-b04c-11e4-871a-4280a8dd28b9.png)

**Comment by IonicaBizau** [comment] 2015-02-09 16:18
OK! Let's try `alias`:

```sh
do_git() {
  cmd=$1
  shift
  extra=""

  quoted_args=""
  whitespace="[[:space:]]"
  for i in "$@"
  do
      quoted_args="$quoted_args \"$i\""
  done

  cmdToRun="git "$cmd" $quoted_args"
  cmdToRun=`echo $cmdToRun | sed -e 's/^ *//' -e 's/ *$//'`
  echo ">>> $cmdToRun"
  bash -c $cmdToRun
  if [ $? -eq 0 ]; then
    # Commit stats
    if [ "$cmd" == "commit" ]; then
      commit_hash=`git rev-parse HEAD`
      repo_url=`git config --get remote.origin.url`
      commit_date=`git log -1 --format=%cd`
      commit_data="\"{ \"date\": \"$commit_date\", \"url\": \"$repo_url\", \"hash\": \"$commit_hash\" }\""
      git-stats --record "$commit_data"
    fi
  fi
}

alias git="do_git"
```

**Comment by atuttle** [comment] 2015-02-09 16:19
![image](https://cloud.githubusercontent.com/assets/46990/6110106/90559a28-b04d-11e4-8797-88ba448fc1cc.png)

**Comment by IonicaBizau** [comment] 2015-02-09 16:43
This is called screenshare via GitHub comments. :smile: The below code works fine on Linux.

```sh
git() {
  cmd=$1
  shift
  extra=""

  quoted_args=""
  whitespace="[[:space:]]"
  for i in "$@"
  do
      quoted_args="$quoted_args \"$i\""
  done

  cmdToRun="command git "$cmd" $quoted_args"
  cmdToRun=`echo $cmdToRun | sed -e 's/^ *//' -e 's/ *$//'`
  echo ">>> $cmdToRun"
  $cmdToRun
  echo $?
  if [ $? -eq 0 ]; then
    # Commit stats
    if [ "$cmd" == "commit" ]; then
      commit_hash=`git rev-parse HEAD`
      repo_url=`git config --get remote.origin.url`
      commit_date=`git log -1 --format=%cd`
      commit_data="\"{ \"date\": \"$commit_date\", \"url\": \"$repo_url\", \"hash\": \"$commit_hash\" }\""
      git-stats --record "$commit_data"
    fi
  fi
}
```

**Comment by atuttle** [comment] 2015-02-09 16:48
Unfortunately still not working:

![image](https://cloud.githubusercontent.com/assets/46990/6110707/84c8802c-b051-11e4-9f3c-342226494b6b.png)

I may have to give up hope on this for now, and just try to remember to do an import before I want to view the stats.

**Comment by IonicaBizau** [comment] 2015-02-09 16:49
Maybe some OS X geeks will see this and come with a fix! :smile:

**Comment by cwebster2** [comment] 2015-02-10 03:39
This isn't an OS X bug.  This same issue exists using zsh on linux (tested with zsh 5.0.5 on linux and OS X).  Your function works properly on OS X with bash (tested with bash 3.2.53 on OS X)

**Comment by IonicaBizau** [comment] 2015-02-10 06:18
I couldn't reproduce it in zsh, but anyway I'm removing the `OS X` label. This will probably be fixed via #4.

**Comment by IonicaBizau** [comment] 2015-02-10 09:09
Run [this script on your machine](https://github.com/IonicaBizau/git-stats/blob/git-hooks/scripts/init-git-post-commit). It will add the `post-commit` hook.

Then do `git init` in all your repositories before committing anything.

BTW, does the importer tool work on Mac?

**Comment by revolt666** [comment] 2015-02-10 13:17
@IonicaBizau, It does work on Mac, but for some reason, it only imports a couple of the commits. Is there a restriction limit set by default?

**Comment by IonicaBizau** [comment] 2015-02-10 13:19
@revolt666 The [git-stats-importer](https://github.com/IonicaBizau/git-stats-importer) tool imports only your commits, it filters them based on the email address you have set.

```sh
$ git config user.email
```

This will output the email address that `git-stats-importer` uses. No other commits are imported.

**Comment by revolt666** [comment] 2015-02-10 13:23
Oh, forgot about that. Can't it get all the commits? Because I'm the only developer but I forgot _(or didn't know how)_ to change the email for a couple of months, and I would be more interested for a general calendar, knowing that the project was being developed by one person at a time.

**Comment by IonicaBizau** [comment] 2015-02-10 13:28
@revolt666 Sure, if you hack it! :smirk: 

You just need to remove [this property](https://github.com/IonicaBizau/git-stats-importer/blob/bfdad400a2ec208cbb8a16572fb9411d40b51aa9/bin/git-stats-importer#L50).

So:

 - clone the git-stats-importer
 - run `npm install` there
 - go to the repository you want to import
 - run `~/path/to/git-stats-importer/bin/git-stats-importer` and it should work

**Comment by revolt666** [comment] 2015-02-10 13:36
@IonicaBizau, Awesome, I will try it later on. Thanks for the detailed guide too :D

**Comment by rambo-panda** [comment] 2015-02-10 14:36
mac 10.10.2 
zsh
have The same problem

**Comment by IonicaBizau** [comment] 2015-02-10 14:38
@rambo-panda Even using the git hooks? :open_mouth:

**Comment by IonicaBizau** [comment] 2015-02-10 17:21
@atuttle Did you try the git hooks version?

**Comment by atuttle** [comment] 2015-02-10 17:46
Not yet, swamped at work.

Adam

**Closed** 2015-02-11 20:09 UTC
Labels: bug

**Comment by atuttle** [comment] 2015-02-11 22:24
I've just had a chance to try the script. It doesn't cause any errors, which is good, but it doesn't seem to capture my commits either.

I've run it, and it did create `~/.git-templates/hooks/post-commit`, and I did a `git init` in the root of one of my existing repositories, but subsequent commits didn't seem to take. I added a simple echo line to the global post-commit hook, and it doesn't appear to be running.

**Comment by IonicaBizau** [comment] 2015-02-12 05:58
> I added a simple echo line to the global post-commit hook, and it doesn't appear to be running.

Add it in `./.git/hooks/post-commit` script. If you edit the global hook you need to do: `rm -rf .git/hooks && git init`.

Hmmm, it should work. I tested it on OS X Yosemite in virtual machine (also in zsh).

Can you confirm that at least the `git-stats-importer` is working properly?

**Comment by atuttle** [comment] 2015-02-12 15:04
`git-stats-importer` has been working for me.

**Comment by IonicaBizau** [comment] 2015-02-12 15:15
The beginning of good news. :smile: 

Run the following commands, exactly like below.

```sh
$ mkdir foo
$ cd foo
$ git init
$ git-stats # Store the total number of commits
$ echo "foo" > foo
$ git remote add foo
$ git add .
$ git commit -m 'initial'
$ git-stats # Check if the total number is with one more
```

If this doesn't work in zsh, check if it work out of zsh.

**Comment by atuttle** [comment] 2015-02-12 15:24
I think I was missing the `rm -rf .git/hooks` step before. I did a `git init` in one of my repos but that didn't update the hooks. Seems to be working now.

**Comment by IonicaBizau** [comment] 2015-02-12 15:27
Cooool! :+1: 

`git init` does update the hooks (at least on Linux, but I tested it on OS X Yosemite in a virtual machine), but it doesn't override them. So, if you already have `post-commit` hook in your repo, `git init` will not bring the one from `~/.git-templates/hooks/post-commit`.
