### ISSUE TITLE
Unable to print git-stats --athors to file

### ISSUE THREAD

**Issue by Gurran** [IonicaBizau/git-stats#149] opened 2019-04-30 12:52 UTC
Hi!

I want to somehow export the piechart generated from 

`git-stats --authors`

When trying to pipe stdOut to file I get the following error:

<details>
<summary>Error Message</summary>

```bash
TypeError: Cannot set property 'NaN' of undefined
    at new CliGraph (/usr/local/lib/node_modules/git-stats/node_modules/cli-graph/lib/index.js:63:54)
    at new CliCircle (/usr/local/lib/node_modules/git-stats/node_modules/cli-circle/lib/index.js:35:18)
    at CliPie.toString (/usr/local/lib/node_modules/git-stats/node_modules/cli-pie/lib/index.js:170:18)
    at /usr/local/lib/node_modules/git-stats/lib/index.js:614:87
    at /usr/local/lib/node_modules/git-stats/lib/index.js:550:9
    at LimitIt. (/usr/local/lib/node_modules/git-stats/node_modules/gry/lib/index.js:85:17)
    at /usr/local/lib/node_modules/git-stats/node_modules/limit-it/lib/index.js:138:20
    at ChildProcess.exithandler (child_process.js:290:7)
    at ChildProcess.emit (events.js:193:13)
    at maybeClose (internal/child_process.js:999:16)
```
</details>

It seems like the output isn't characters but colors? How can I export this?

**Comment by Gurran** [comment] 2019-07-26 12:34
Is there any other way to export the data? I want to export the data to analyse, so I just need a CSV.

**Comment by IonicaBizau** [comment] 2019-12-18 21:45
Duplicate of #114.

**Closed by IonicaBizau** 2019-12-18 21:45 UTC
