### ISSUE TITLE
Show stats for all contributions

### ISSUE THREAD

**Issue by sourcerer-mike** [IonicaBizau/git-stats#27] opened 2015-02-18 12:58 UTC
Please make an option, so that all commits count not only the own.

**Comment by IonicaBizau** [comment] 2015-02-18 13:01
Can you please add more details to your question?

What do graph would you like more precisely?

**Comment by atuttle** [comment] 2015-02-18 13:30
I think he's requesting that it show stats from all committers, not just the current user.

**Comment by IonicaBizau** [comment] 2015-02-18 13:31
If so, how should the graph look like? Maybe different colors? Or one graph for each commiter?

**Comment by atuttle** [comment] 2015-02-18 13:54
I think it's fine to leave it visually how it is. When viewing all contributors, you're looking at global activity level, not at activity level by person. I think it should be a flag, like `--all` to see them.

**Comment by IonicaBizau** [comment] 2015-02-18 13:56
Then, greener will mean more global activity (from all committers), right?

**Comment by atuttle** [comment] 2015-02-18 14:24
Exactly.

**Comment by sourcerer-mike** [comment] 2015-02-19 18:17
Sorry! Didn't watch my mails. Exactly, atuttle got it - thanks!
All commits from all people with the same look as it is now for one person.

Cheers!

**Comment by sambrightman** [comment] 2015-04-08 07:41
I was thinking more along the lines of a breakdown per-author. Would that now be best suited for a different Issue? Seems useful to be able to see who is most active in a project/module.

**Comment by IonicaBizau** [comment] 2015-04-08 07:48
@sambrightman That's a good point. I'd say to open a new issue for that. A quick alternative would be to alias `authors` with `git shortlog -s -n --all`.

In `.gitconfig` I have:

```gitconfig
[alias]
    authors = shortlog -s -n --all
```

**Comment by IonicaBizau** [comment] 2015-04-08 07:48
aA

**Comment by IonicaBizau** [comment] 2015-07-08 09:02
@sambrightman This is now supported in `v2.0.0` branch -- use `git stats --authors` to display a nice pie with the authors activity. /cc #51.

@atuttle @sourcerer-mike In #55 I implemented this feature. :bell: I'm closing this issue as duplicate of #13.

**Closed by IonicaBizau** 2015-07-08 09:02 UTC
Labels: Brainstorm
